### ISSUE TITLE
Лаб1 @ahahahahahahahaker 

### ISSUE THREAD

**Issue by ananasn** [ahahahahahahahaker/lab1#1]
@ahahahahahahahaker 
Все указанные ниже замечания нужно исправить.

Замечания:

1.  Программа выдает ошибку. Исправьте ошибку. Ответьте на вопрос, что принимает функция `int(par1, par2)` в качестве второго параметра? Зачем вы заменяете точку на запятую? (Ответ напишите в ответ здесь)
![Снимок экрана от 2023-10-09 02-51-54](https://github.com/ahahahahahahahaker/lab1/assets/8919470/3db869cc-a54e-47e1-b112-9d58879ba47b)

2. В программе названия переменных должны иметь смысл, название отражает суть того, что содержит переменная. Отсюда применение переменных с  названиями `k`,` a`, `n` недопустимо. Например, `a` стоит назвать `search_request`.
 
3. Не используйте магические числа (типа `150, 30, 13` и тд) в программе, суть которых понятна только вам. Обозначайте их как константы. Константы обычно указываются вначале программы после блока импортов. Пример:
  ```python
  import csv
  
  PRICE_LOWER_LIM = 150
  MAX_NAME = 30
  
  ....
  ```

4. Бесполезная переменная `n`

5. Оформление не по `PEP8`. Операторы обрамляются пробелами. Пример `k+=1` должно быть `k += 1`. Аналогичное в нескольких местах. Ознакомьтесь с этим разделом PEP8 https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements
6. Используйте `f-строки`, это более предпочтительнее
```python
print(f'Кол-во записей: {entries_num}')
```

7. Используйте один вид кавычек( двойные `"` или одинарные `'`) для обозначения строковых литералов. Это делает код аккуратнее и более читаемым. 

8.  Записи типа `row[7], row[4], row[1]` плохо читаемы, лучше давать таким объектам названия и использовать по названию. Пример:
  ```python
  author_name = row[4]
  if author_name == search_request:
      ...
  ```
9. Это можно сократить до одной строки
  ```python
    print('введите ФИО автора:')
    a=input()
  
   # Лучше так
   search_request = input("Введите ФИО автора:\n")
  ```

10. Где это задание?
```Реализовать генератор библиографических ссылок вида <автор>. <название> - <год> для 20 записей. Записи выбрать произвольно. Список сохраняется как отдельный файл текстового формата с нумерацией строк.```

**Comment by ahahahahahahahaker** [comment]
Программу отладил, ошибки исправил. на счет запятой: когда сравнивал цену, не получалось сделать int из записи типа [144.5]. Думал что замена точки на запятую решит проблему но вроде не получилось. Подскажите как из таких видов записи делать int?

**Comment by ananasn** [comment]
У вас в `price` лежит не `[144.5]`  (список содержащий float) как вы написали, а строка вида `"144.5"`. Просто приводите ее к `float` таким образом `float(price)` и сравнивайте хоть с `float`, хоть c `int`. Думаю, что ошибка у вас вылезала, потому что вы пытались достать цену из заголовка и получали внутри переменной `price` строку `'Цена поступления'`. Заголовок можно пропустить выполнив `next(reader)` перед циклом. Это позволит итератору "перешагнуть" первую строку заголовка таблицы.

**Comment by ananasn** [comment]
Исправьте условие на нормальное :)
